[phases.setup]
nixPkgs = [
  'python311',
  'python311Packages.pip',
  'python311Packages.django',
  'python311Packages.djangorestframework',
  'python311Packages.django-cors-headers',
  'python311Packages.gunicorn'
]

[start]
cmd = 'python3 -m gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT'
