[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.setuptools']
aptPkgs = []

[phases.install]
cmds = ['pip install -r requirements.txt --break-system-packages']

[variables]
DJANGO_SETTINGS_MODULE = 'backend.settings_prod'

[start]
cmd = 'python3 -m gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --access-logfile - --error-logfile - backend.wsgi:application'
