[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.setuptools']

[phases.install]
cmds = [
  'pip install -r requirements.txt --break-system-packages',
  'python3 -c "import sys; print(\"Python path:\", sys.path)"',
  'python3 -c "import gunicorn; print(\"Gunicorn found\")" || echo "Gunicorn import failed"'
]

[variables]
DJANGO_SETTINGS_MODULE = 'backend.settings_prod'

[start]
cmd = 'python3 -m gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --access-logfile - --error-logfile - backend.wsgi:application'
