[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.setuptools']

[phases.install]
cmds = ['pip install -r requirements.txt --break-system-packages']

[start]
cmd = 'python3 manage.py migrate --settings=backend.settings_prod && python3 -m gunicorn --env DJANGO_SETTINGS_MODULE=backend.settings_prod backend.wsgi:application --bind 0.0.0.0:$PORT'
