[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.setuptools', 'python311Packages.wheel']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[start]
cmd = 'python3 -m gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT'
