"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.
Updated to Django 5.2.5

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable is not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "0") == "1"

# .env.example ships a working local config so `cp .env.example .env` is enough to
# get started — which also makes it possible to copy that file straight to a real
# deployment. Fail loudly rather than serve production traffic with a key that is
# published in the repo.
DEV_PLACEHOLDER_SECRET_KEY = "dev-only-insecure-key-replace-me-in-production"
if not DEBUG and SECRET_KEY == DEV_PLACEHOLDER_SECRET_KEY:
    raise RuntimeError(
        "SECRET_KEY is still the placeholder from .env.example. Generate a real one: "
        "python -c \"from django.core.management.utils import get_random_secret_key; "
        "print(get_random_secret_key())\""
    )

# Strip whitespace from each entry so Render env-var copy-paste typos don't break host validation
ALLOWED_HOSTS = (
    [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]
    or ["localhost", "127.0.0.1"]
)
if not DEBUG:
    ALLOWED_HOSTS += ["gamified-app-p9ao.onrender.com", ".onrender.com"]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # For React frontend
    'rest_framework',  # For API
    'rest_framework.authtoken',  # Token authentication
    'backend',  # Main app (contains models, views, etc.)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set")

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=0,
        # Only enforce SSL in production — local/CI runs (DEBUG=1) commonly
        # point at plain sqlite or an unencrypted test database. This is a
        # fallback only: if DATABASE_URL itself has ?sslmode=require (as the
        # production Neon URL does), that takes precedence regardless of
        # DEBUG, so a DEBUG=1 slip in production does not by itself turn
        # off SSL there.
        ssl_require=not DEBUG,
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise settings for serving static files (Django 5.2+ format)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'backend.User'

# CORS settings for React frontend
_cors_raw = os.environ.get('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = (
    [o.strip() for o in _cors_raw.split(',') if o.strip()]
    if _cors_raw
    else (
        ["http://localhost:5173", "http://localhost:3000"] if DEBUG
        else ["https://levelup-jet.vercel.app"]
    )
)

# CSRF settings for cross-origin requests
if not DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "https://gamified-app-p9ao.onrender.com",
        "https://levelup-jet.vercel.app",
    ]

    # Render terminates TLS at its proxy and forwards over plain HTTP, so
    # request.is_secure() is False for every request unless Django is told to
    # trust the forwarded header. Without this line SECURE_SSL_REDIRECT below
    # sees an insecure request, redirects to HTTPS, and the proxy forwards the
    # result back over HTTP — an infinite loop. This has to come first.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True

    # Start HSTS at one hour rather than the usual year. A browser that has
    # seen this header refuses plain HTTP for the whole max-age and there is no
    # way to call that back, so the value is raised deliberately once the
    # HTTPS-only setup has proven itself, not on day one.
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

    # The API is token-authenticated, so these cookies matter for the Django
    # admin rather than the app itself — which is exactly the session worth
    # protecting.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"

    # Both of these are deliberate, so they are silenced rather than left as
    # standing warnings — that way CI can treat any *new* warning as a failure.
    #   W005 includeSubDomains: the deployed host has no subdomains, and
    #        asserting it would outlive a future move to a custom domain whose
    #        subdomains may not all be HTTPS.
    #   W021 preload: submitting to the browser preload list is effectively
    #        irreversible, which is not a commitment to make while HSTS is
    #        still at a one-hour max-age.
    SILENCED_SYSTEM_CHECKS = ["security.W005", "security.W021"]

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # ScopedRateThrottle only affects views that declare a throttle_scope,
    # so regular task/stat endpoints stay unthrottled.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # The System chat endpoint calls an external AI provider — rate-limited
        # on the free NVIDIA default, billed per request on Anthropic. Capped
        # per account AND per IP, because guest accounts are free to create and
        # could otherwise be rotated past a per-account limit.
        'system_chat': '15/hour',
        'system_chat_ip': '30/hour',
        # Account creation (register + guest login) is IP-throttled for the
        # same reason.
        'account_create': '10/hour',
        # Failed logins are the cheap half of credential stuffing, so this is
        # deliberately tighter than account creation. Legitimate users rarely
        # need more than a handful of attempts in an hour.
        'login': '20/hour',
        # Task completion writes EXP, attributes and rows. Nothing capped it,
        # and the time-limited branch creates a new Task per call with no
        # per-day limit, so a loop could farm stats and fill the database.
        # Set well above real use: a heavy day is a few dozen completions.
        'task_write': '200/hour',
    },
    # Render sits behind one reverse proxy; without this, every client would
    # share the proxy's IP and IP throttles would lump all users together.
    'NUM_PROXIES': 1,
}

# Throttle counters must be shared across workers and survive restarts, so
# they live in the database rather than the default per-process memory cache.
# Requires the cache table: python manage.py createcachetable
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache',
    }
}

# Django's default configuration only surfaces logs when DEBUG is on, so in
# production every logger.exception() call in views.py went nowhere. Render
# captures stdout, so a console handler is all that is needed to make them
# visible — without it, the switch from returning str(e) to logging it would
# have traded a leak for silence.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'backend': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
