# Generated by Django 5.2.4 on 2025-08-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_current_streak_user_last_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_tasks_completed_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_all_tasks_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
