# Generated by Django 5.2.5 on 2025-08-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_all_tasks_completed_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attribute',
            field=models.CharField(choices=[('intelligence', 'Intelligence'), ('discipline', 'Discipline'), ('energy', 'Energy'), ('social', 'Social'), ('wellness', 'Wellness'), ('stress', 'Stress')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='name',
            field=models.CharField(choices=[('intelligence', 'Intelligence'), ('discipline', 'Discipline'), ('energy', 'Energy'), ('social', 'Social'), ('wellness', 'Wellness'), ('stress', 'Stress')], max_length=20),
        ),
    ]
