# Generated by Django 5.2.5 on 2025-08-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_task_attribute_alter_userattribute_name'),
    ]

    operations = [
        # Remove unused Reward and UserReward models
        migrations.DeleteModel(
            name='UserReward',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        # Remove unused SubGoal model
        migrations.DeleteModel(
            name='SubGoal',
        ),
        # Remove unused fields from Task model
        migrations.RemoveField(
            model_name='task',
            name='created_by_ai',
        ),
        # Remove unused fields from User model
        migrations.RemoveField(
            model_name='user',
            name='all_tasks_completed_today',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_all_tasks_completed_date',
        ),
        # Remove unused fields from UserTaskLog model
        migrations.RemoveField(
            model_name='usertasklog',
            name='earned_points',
        ),
    ]
