# Generated by Django 5.2.5 on 2026-05-20 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20250827_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mission_type',
            field=models.CharField(choices=[('daily', 'Daily Quest'), ('main', 'Main Quest'), ('urgent', 'Urgent Quest'), ('punishment', 'Punishment Quest'), ('hidden', 'Hidden Quest'), ('system_generated', 'System Generated')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='system_flavor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='system_personality',
            field=models.CharField(choices=[('logical', 'Logical'), ('mentor', 'Mentor'), ('tsundere', 'Tsundere'), ('drill_sergeant', 'Drill Sergeant')], default='logical', max_length=20),
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('daily_brief', 'Daily Brief'), ('evening_eval', 'Evening Evaluation'), ('punishment', 'Punishment'), ('chat_response', 'Chat Response'), ('alert', 'Alert')], max_length=20)),
                ('content', models.TextField()),
                ('missions_issued', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(choices=[('iron_will', '鐵血意志者'), ('early_bird', '晨曦先鋒'), ('comeback_king', '不屈的宿主'), ('consistent_scholar', '博學多識'), ('overachiever', '超額成就者'), ('first_system_contact', '初次連線')], max_length=30)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Title',
                'verbose_name_plural': 'User Titles',
                'unique_together': {('user', 'title_key')},
            },
        ),
    ]
