# Generated by Django 5.2.5 on 2026-09-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_task_mission_type_task_system_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertitle',
            name='title_key',
            field=models.CharField(choices=[('iron_will', 'Iron Will'), ('early_bird', 'Early Bird'), ('comeback_king', 'Comeback King'), ('consistent_scholar', 'Consistent Scholar'), ('overachiever', 'Overachiever'), ('first_system_contact', 'First Contact')], max_length=30),
        ),
    ]
