# Generated by Django 5.2.5 on 2026-09-14 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_usertitle_title_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Measurement Report',
                'verbose_name_plural': 'Measurement Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_type', models.CharField(choices=[('outcome', 'Outcome'), ('cumulative', 'Cumulative'), ('measurable', 'Measurable')], default='outcome', max_length=12)),
                ('target_count', models.PositiveIntegerField(blank=True, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_direction', models.CharField(blank=True, choices=[('at_least', 'At least'), ('at_most', 'At most')], default='', max_length=8)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('outcome_note', models.CharField(blank=True, default='', max_length=300)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('completed', 'Completed')], default='locked', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='completion_type',
            field=models.CharField(choices=[('outcome', 'Outcome'), ('cumulative', 'Cumulative'), ('measurable', 'Measurable')], default='outcome', max_length=12),
        ),
        migrations.AddField(
            model_name='goal',
            name='outcome_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='goal',
            name='path_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_direction',
            field=models.CharField(blank=True, choices=[('at_least', 'At least'), ('at_most', 'At most')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_completed', False), ('path_confirmed_at__isnull', False)), fields=('user',), name='one_current_path_per_user'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='backend.goal'),
        ),
        migrations.AddField(
            model_name='measurementreport',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='backend.milestone'),
        ),
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='backend.milestone'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('goal', 'position'), name='unique_milestone_position'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('goal',), name='one_active_milestone_per_goal'),
        ),
    ]
